# Generated by Django 2.0.9 on 2018-11-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idF', models.IntegerField()),
                ('nomeF', models.CharField(max_length=200)),
                ('qtdF', models.IntegerField()),
            ],
        ),
    ]
