# Generated by Django 2.0.9 on 2018-11-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ES', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='CadastroF',
        ),
    ]
